---
- name: instaling webserver
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with items:
    - "{{ package_manager }}"
    - "{{ web_server }}"
- name: starting the webserver
  service: 
    name:"{{ web_server }}"
    state: started
- name: copying web content to doc root
  copy:
    src: "{{ source_file }}"
    dest: "{{ doc_root }}"
    mode=0644
- name: restart webserver
  service:
    name: "{{ web_server}}"
    state: restarted